
# Default effect file, used for all objects if not overridden

Vertex:
    template: default
    dependencies:
        - Includes/PositionReconstruction.inc.glsl
    inout:
        - uniform vec3 cameraPos;
        - uniform mat4 currentMVP;

    inject:
        vertex:
            // vOutput.position += vec3(0.1, 0.2, 2.3);

Fragment.GBuffer:
    template: default
    inject:
        material:
            m.diffuse *= 2.0;
            m.specular = 0.3;

Fragment.Shadows:
    template: default

Fragment.Voxelize:
    template: default
